transport-nantes/tn_web

.gitignore
transport_nantes/asso_tn/templates/asso_tn/base_transport_nantes.html
transport_nantes/asso_tn/templates/asso_tn/panel/projects.html
transport_nantes/transport_nantes/settings.py
transport_nantes/transport_nantes/urls_tn.py
transport_nantes/velopolitain/templates/velopolitain/gilets.html

Part of #121 
Replaced urls linked to it with # 
Edited settings.py
Edited .gitgnore

Fix grand_nantes deletion #121

---

transport_nantes/topicblog/tests.py

Part of #78
Tests http response on the main page

Add main page status code test

---

transport_nantes/surveys/templates/surveys/survey.html

Should be territory-dependant
Quick hack part of #143

Changed Commune for territoire

---

transport_nantes/surveys/templates/surveys/survey.html
transport_nantes/surveys/views.py

Quick hack to make the Christelle Morancais responses usable.

Render survey responses with markdown

---

transport_nantes/geoplan/views.py

Modification in model did make required to re-assign
the value of layer_type in the database.
Add an error raise in case of incorrect value for layer_type.
Part of #118

Fix layer style following model modification

---

transport_nantes/topicblog/templates/topicblog/topicblogitem_list.html
transport_nantes/topicblog/urls.py
transport_nantes/topicblog/views.py

Add a List view to TopicBlog
At allows the user to see a list of all TopicBlogItems OR filter the results to be limited to those containing a specific slug. 
Follows PR #176

Topic blog v2 list

---

transport_nantes/topicblog/tests.py

Add tests to each view in the URL pattern : 
- TopicBlogItemEdit
- TopicBlogItemView
- TopicBlogItemList
it tests status code, the item_sort_key of the loaded item and the length of queries when appropriate. 
Follows PR #182

Tb v2 tests

---

transport_nantes/transport_nantes/settings.py

Adds timestamps to logger. 
Example of timestamp : [2021-09-01 08:34:51,046]

Add timestamps to each log line

---

transport_nantes/topicblog/tests.py
transport_nantes/topicblog/views.py

Ask for login before accessing edit and list view. 
tests assume the user is logged in.

T bv2 login

---

transport_nantes/asso_tn/templates/asso_tn/hero_base_transport_nantes.html
transport_nantes/authentication/templates/authentication/account_activation_invalid.html
transport_nantes/authentication/templates/authentication/account_activation_sent.html
transport_nantes/authentication/templates/authentication/home.html
transport_nantes/authentication/templates/authentication/login.html
transport_nantes/authentication/templates/authentication/profile.html
transport_nantes/surveys/templates/surveys/questionnaire.html
transport_nantes/velopolitain_observatoire/templates/velopolitain_observatoire/comment-faire.html
transport_nantes/velopolitain_observatoire/templates/velopolitain_observatoire/count_app.html
transport_nantes/velopolitain_observatoire/templates/velopolitain_observatoire/count_form.html
transport_nantes/velopolitain_observatoire/templates/velopolitain_observatoire/faq.html
transport_nantes/velopolitain_observatoire/templates/velopolitain_observatoire/index.html

With that the templates are accessible and I received a fake link in the console to "activate", from what I've seen it might work as it used to. 
closes #224

Replaced base_transport_nantes with base_mobilitain in templates.

---

transport_nantes/topicblog/tests_auth_users.py
transport_nantes/topicblog/tests_staff_users.py

Update TBv2 tests to englobe the is_staff requirement.

---

transport_nantes/topicblog/templates/topicblog/tb_item_edit.html

Improve responsive of TBv2's creation/edition form

---

transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html
transport_nantes/topicblog/models.py
transport_nantes/topicblog/views.py

Fix for invalid image links. 
Also minor code cleaning to abide PEP8
Closes #238

Fix og cards 238

---

transport_nantes/stripe_app/views.py

Some users only ever gave their mail address, so if they happen
to give us their name, we can use it to update their name in database.
Of course, if they did give a name that is different, we leave it alone.
Closes #178

Add function to update unamed Users on donation

---

transport_nantes/stripe_app/models.py
transport_nantes/stripe_app/views.py

People that have got to checkout session but did not complete it
within 24 hours will be saved in database for later contact.
Closes #247

Capture expired checkout session into database.

---

transport_nantes/asso_tn/static/asso_tn/mobilitains.css
transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html
transport_nantes/asso_tn/urls.py
transport_nantes/topicblog/views.py

The banner is closable upon clicking X.
Text is modifiable in the View.

Add a banner promoting our Crowdfunding

---

transport_nantes/Makefile

Add simple makefile to codify dev workflow

---

README.md
Vagrantfile
transport_nantes/transport_nantes/settings_local.py.DEV.template

MVP of improved readme, to allow contributors to set up a local environment easily. 
Part of #310

Improve onboarding

---

transport_nantes/topicblog/templates/topicblog/topicblogitem_list_one.html
transport_nantes/topicblog/views.py

Also include modification date in sort order.  Date modified is also
date created for us.
Part of #337.

Add id field to slug-specific list view

---

transport_nantes/topicblog/templates/topicblog/topicblogitem_list.html
transport_nantes/topicblog/templates/topicblog/topicblogitem_list_one.html
transport_nantes/topicblog/views.py

Simplify display.
Add sort by date_modified DESC.
Add date_modified to one-slug ListView.
Closes #337.

Unique slugs in the all-slug ListView

---

transport_nantes/topicblog/templates/topicblog/communique_presse_1.html
transport_nantes/topicblog/templates/topicblog/content.html

Revert back to enabled the list styles.
This change was too rigid and difficult to use.
Part of #336

Revert change on list style

---

transport_nantes/asso_tn/templatetags/don.py

Changes the old style external link button using bootstrap to our chartered button. 
Also some cleanup to respect PEP8.

External links style

---

transport_nantes/stripe_app/views.py

The logger didn't accept extra arguments as additional text like print do, fixed it so now we have full details about the events going through our webhook. 
Part of #233

Fix logging messages to handle variables.

---

transport_nantes/topicblog/views.py

Closes #331 
Reverts the unpublishing upon hitting save button. 
Also some code cleaning to abide by PEP8

Remove unpublish

---

transport_nantes/asso_tn/middleware/sessionCookie.py
transport_nantes/asso_tn/static/asso_tn/mobilitains.css
transport_nantes/topicblog/templates/topicblog/base_topicblog.html
transport_nantes/utm/middleware/utm.py
transport_nantes/utm/templates/utm/visit_overview.html
transport_nantes/utm/templatetags/utm.py
transport_nantes/utm/tests.py

Add some basic visitor stats for admins.
Closes #347.

Utm visit 347

---

transport_nantes/Makefile
transport_nantes/asso_tn/tests.py
transport_nantes/asso_tn/utils.py
transport_nantes/authentication/forms.py
transport_nantes/authentication/templates/authentication/account_activation_email.html
transport_nantes/authentication/templates/authentication/account_activation_invalid.html
transport_nantes/authentication/templates/authentication/account_activation_sent.html
transport_nantes/authentication/templates/authentication/home.html
transport_nantes/authentication/templates/authentication/login.html
transport_nantes/authentication/templates/authentication/mail_confirmed.html
transport_nantes/authentication/templates/authentication/password_login.html
transport_nantes/authentication/templates/authentication/profile.html
transport_nantes/authentication/tests.py
transport_nantes/authentication/tests_auth.py
transport_nantes/authentication/urls.py
transport_nantes/authentication/views.py
transport_nantes/topicblog/tests_staff_users.py
transport_nantes/transport_nantes/settings.py

Branch cleaned and ready for PR.

Login 119 v2

---

transport_nantes/topicblog/tn_links.py

Simplify setting context in markdown

---

transport_nantes/topicblog/templates/topicblog/topicblogitem_list.html
transport_nantes/topicblog/templates/topicblog/topicblogitem_list_one.html
transport_nantes/topicblog/views.py

Correctly show published item if there is one.
Sort correctly (by pub date, then mod date).
Show creating user as such, not as publisher.
Closes #438.

Fix and improve TBObject list view

---

transport_nantes/mailing_list/templates/mailing_list/merci_m.html

Remove an awkward donation pitch, be a bit more laid back and show the
projects we're working on to encourage getting to know us.

Spruce up the "thank you for signing up" page

---

transport_nantes/asso_tn/middleware/default_context.py
transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html
transport_nantes/asso_tn/templatetags/og_twitter.py
transport_nantes/asso_tn/tests_og_twitter.py

Hello I do 3 commit for solve this issue:
1. I rename variable in the middleware
2. I implement the solution on the base template in asso_tn
3. I add unit test for testing the meta in the template

Og twitter template middleware

---

transport_nantes/.coveragerc

Remove test file from the coverage

Improve the coverage filter

---

.github/workflows/django.yml

Automating test and coverage before push and pull request
Fix #343

Add django github-action

---

transport_nantes/press/templates/press/press_list.html
transport_nantes/press/views.py

Add pagination on press listview

Add pagination on press listview

---

transport_nantes/topicblog/tests_topic_blog.py
transport_nantes/topicblog/tests_topic_blog_form.py

The coverage test is now at 100% for topicblog model and 95% (9 lines that I can't acces) for topicblog view. 
1. https://github.com/transport-nantes/tn_web/blob/35af2e6d9df2f8c2b1fdd80f8458685c78eb91d5/transport_nantes/topicblog/views.py#L101-L102
2. https://github.com/transport-nantes/tn_web/blob/35af2e6d9df2f8c2b1fdd80f8458685c78eb91d5/transport_nantes/topicblog/views.py#L108-L109
3. https://github.com/transport-nantes/tn_web/blob/35af2e6d9df2f8c2b1fdd80f8458685c78eb91d5/transport_nantes/topicblog/views.py#L167-L171
4. https://github.com/transport-nantes/tn_web/blob/35af2e6d9df2f8c2b1fdd80f8458685c78eb91d5/transport_nantes/topicblog/views.py#L345

Improve the test coverage of topicblog model and view

---

transport_nantes/stripe_app/tests.py
transport_nantes/stripe_app/views.py

Current coverage of stripe_app's views.py is now at 88%, last lines missing are mostly
error catch and their log lines, so few holes but still good enough
to be reassured that a normal flow runs smoothly for now.
Part of #197

Add Selenium test to stripe app

---

transport_nantes/press/templates/press/press_list_view.html
transport_nantes/press/templates/press/table_list.html
transport_nantes/press/views.py

The first and second commit is there for no merging conflic.
On the last commit i add link on newspaper that open on new tab and filter the table.

Add filter on newspaper name

---

transport_nantes/mailing_list/forms.py
transport_nantes/mailing_list/templates/mailing_list/panel/mailing_list.html
transport_nantes/mailing_list/templatetags/newsletter.py
transport_nantes/mailing_list/urls.py
transport_nantes/mailing_list/views.py

I use a get method to send the mail and the mailingslist to the last part but I dont know if this is the best way for do this. I think about session for do this too but I dont know what is the best.

Improve the mailing list subcription

---

transport_nantes/mailing_list/events.py
transport_nantes/mailing_list/views.py

Add subscribe and unsubscribe functions and use the subscribe fonction on views.

Improve mailing list subscrition and unsubscription

---

transport_nantes/asso_tn/tests_og_twitter.py

Use the static function for turn string into static url and use media url for the media.
Closes #503

Improve the test of the static and media url

---

transport_nantes/mailing_list/forms.py
transport_nantes/mailing_list/templates/mailing_list/mailing_list_user_status.html
transport_nantes/mailing_list/templates/mailing_list/status/hidden_form.html
transport_nantes/mailing_list/templates/mailing_list/status/list_m.html
transport_nantes/mailing_list/templates/mailing_list/status/pagination.html
transport_nantes/mailing_list/templates/mailing_list/validate_form.html
transport_nantes/mailing_list/tests.py
transport_nantes/mailing_list/urls.py
transport_nantes/mailing_list/views.py

Add status view on mailing list where the user can manage subscription.

Add the user status mailing list page

---

transport_nantes/topicblog/models.py
transport_nantes/topicblog/templates/topicblog/content_launcher.html
transport_nantes/topicblog/views.py

Minor fixes left on the previous PR #529
* Image not displaying properly on TB Launcher
* PEP8 format
* Cleanup by removing unused variables and prints
* Permissions are set

Fix jeff tb stuff

---

transport_nantes/topicblog/forms.py
transport_nantes/topicblog/templates/topicblog/topicblogemail_send_form.html
transport_nantes/topicblog/views.py

Creates a form in which you can select an existing mailing list to send you TBEmail to.
POST isn't handled yet in this commit.

Add GET handling for TBESend

---

transport_nantes/dashboard/forms.py
transport_nantes/dashboard/templates/dashboard/signature.html
transport_nantes/dashboard/urls.py
transport_nantes/dashboard/views.py

Default values are user's info if any, they are overridden by whatever the user would input in the form.
Simply copy paste following the [guide](https://docs.google.com/document/d/13HbNW_dRQElrP3fgEcYDrmw08mqQ6ETWwzj25NNOzr8/edit)

Add a form to generate signatures for emails

---

transport_nantes/asso_tn/utils.py

Our timed tokens were emminently forgeable, although it seemed quite a
lot of work for an adversary to do so for the very little gain.  This
commit addresses that issue by upping (significantly) the amount of
work necessary to forge a timed token.  We believe the difficulty of
forging a timed token is now on a par with the difficulty of breaking
SHA1 or SHA256.
This increases the length of our timed tokens, but we don't currently
consider that to be a problem.

Improve timed token security

---

transport_nantes/topicblog/forms.py
transport_nantes/topicblog/static/topicblog/edit_slug_warning.js
transport_nantes/topicblog/templates/topicblog/tb_item_edit.html

Add a warning if the slug field  change
If this is good i will do the same on other TB

Remove immutable status of slug field in TopicBlog Item

---

transport_nantes/topicblog/templates/topicblog/template_tags/launcher.html
transport_nantes/topicblog/templatetags/launcher.py
transport_nantes/topicblog/templatetags/test_templatags.py

Add the launcher template tags

Add launcher template tags

---

transport_nantes/asso_tn/templates/asso_tn/index.html

We are temporarily hard-coding the slugs to use on the index page.
Use slugs slugs that actually exist in production and that we
currently expect on the index page so that we can test this and make
sure we're happy with the result.

Fix hardcoded s

---

transport_nantes/topicblog/forms.py
transport_nantes/topicblog/models.py
transport_nantes/topicblog/templates/topicblog/content_press.html
transport_nantes/topicblog/templates/topicblog/content_press_mail_client.html
transport_nantes/topicblog/templates/topicblog/topicblogpress_send_form.html
transport_nantes/topicblog/views.py

This branch makes TopicBlogPress items sendable through email using their own template, in the same way TBEmails currently do. 
Beta test is working fine !

Benja 598 make press sendable

---

transport_nantes/topicblog/templates/topicblog/content_launcher.html

- Fix the launcher_image when creating a launcher
- Remove headers banner of content_launcher template

Fix the launcher_image when creating a launcher

---

transport_nantes/topicblog/templatetags/email_tags.py
transport_nantes/topicblog/templatetags/test_templatags.py

CTA button wasn't displayed well on some mailbox

Fix button style on email client

---

transport_nantes/press/form.py

initiate the article_publication_date field with today's date.

Improve PressMentionForm

---

transport_nantes/topicblog/templates/topicblog/base_email.html
transport_nantes/topicblog/templates/topicblog/base_press.html

To suggest there is more after the press of this button, we add
suspension marks ...
Closes #636

Add suspension marks to Envoyer button

---

transport_nantes/topicblog/templates/topicblog/content_email.html
transport_nantes/topicblog/templates/topicblog/content_email_client.html

Add date on top of TBEmails
Closes #632

Add date on top of TBEmails

---

transport_nantes/mailing_list/events.py
transport_nantes/mailing_list/test_events.py

- Fix the user_subscribe_count
- Update the user_subscribe_count test

Fix user_subscribe_count doesn't return a correct number

---

transport_nantes/press/form.py
transport_nantes/press/templates/press/press_list.html
transport_nantes/press/views.py

press add search

---

transport_nantes/press/templates/press/press_list_view.html
transport_nantes/press/views.py

- Update the display and show 30 press mention

Update the display of press:view page

---

transport_nantes/press/views.py

the order by is already set in the model

Remove the order by of press_mention_list

---

transport_nantes/press/templates/press/press_detail.html
transport_nantes/press/templates/press/press_list.html

For help user to know where they will be redirected

Add tooltips for link in press app

---

transport_nantes/topicblog/models.py
transport_nantes/topicblog/templates/topicblog/base_launcher.html

Launcher now has a publish function live every other TB Item
That's a step to #676 
Closes #675

Benja 675 add publish launchers

---

requirements.txt
transport_nantes/transport_nantes/settings.py
transport_nantes/transport_nantes/urls.py

This toolbar allows us to see the SQL queries that Django is running,
and the time it takes to run them.
It also shows us various data, like the context of the request.
See doc : http://django-debug-toolbar.readthedocs.org/en/latest/

Add Django debug toolbar

---

transport_nantes/authentication/templates/authentication/account_activation_email.html
transport_nantes/authentication/views.py

This PR allows the user to access the desired page after login automatically.
This is done by passing the ?next= argument to the token and redirecting to it if present, after being logged in.
Closes  #709

Benja 709 fix login redirect

---

transport_nantes/photo/forms.py

From 
"Exemples : j'y habite, j'y travaille, c'est compliqué, autre..."
to
"Exemples : j'y habite, j'y travaille, c'est compliqué, Aucun mais je vous aime bien :)..."

Modify the placeholder line for Operation pieton's form

---

transport_nantes/photo/templates/photo/photoentry_form.html
transport_nantes/photo/views.py

They have shown interest by participating, so it seems fair to
automatically subscribe them to the operation pieton mailing list.

Make users submitting photos automatically subscribed to mailing list

---

transport_nantes/mailing_list/views.py

The Unsubscription time is set as soon as you click "se désabonner"
in the email, even though you didn't confirm it afterwards.
Closes #688
I'm a bit dubious about why we would save it when on click instead of waiting for the POST on the form ?

Save unsubscription time onclick on unsub link

---

transport_nantes/asso_tn/templates/asso_tn/contact.html
transport_nantes/asso_tn/templates/asso_tn/jobs.html
transport_nantes/authentication/forms.py
transport_nantes/authentication/templates/authentication/account_activation_sent.html
transport_nantes/authentication/templates/authentication/login.html
transport_nantes/clickcollect/forms.py
transport_nantes/mailing_list/forms.py
transport_nantes/surveys/templates/surveys/response_1.html
transport_nantes/surveys/templates/surveys/survey.html
transport_nantes/velopolitain_observatoire/templates/velopolitain_observatoire/comment-faire.html
transport_nantes/velopolitain_observatoire/templates/velopolitain_observatoire/faq.html
transport_nantes/velopolitain_observatoire/templates/velopolitain_observatoire/index.html

Reworded Login page and replaced "mél" with "mail" :wink:

Benja rework login page

---

transport_nantes/topicblog/templates/topicblog/base_email_client.html
transport_nantes/topicblog/templates/topicblog/content_email_client.html
transport_nantes/topicblog/templates/topicblog/content_press_mail_client.html

to balance this, I turned 'Voir sur le site web' in a darker shade of
gray.
Closes #760

Remove gray borders on emails

---

transport_nantes/topicblog/templates/topicblog/content_press.html
transport_nantes/topicblog/templates/topicblog/content_press_mail_client.html

In real life, this should check the database for a configured email
address and even phone number.  But this provides the default
behaviour whilst waiting for that.
This is a small bit of #764.

Quick fix to add default email to press contacts

---

transport_nantes/topicblog/templates/topicblog/content_email_client.html
transport_nantes/topicblog/templates/topicblog/content_press_mail_client.html

Body text wasn't parsed through Markdown

Add Markdown to emails

---

transport_nantes/topicblog/views.py

Fix the SendRecord class of TBSendPress

---

transport_nantes/mailing_list/views.py
transport_nantes/topicblog/tests_topic_blog_form.py
transport_nantes/transport_nantes/settings.py
transport_nantes/transport_nantes/templates/transport_nantes/404.html

This provides a friendlier experience for 404 errors
Error message is provided : 
Fallback
Part of #779

Add 404 page template

---

transport_nantes/topicblog/views.py

We catch the click and open signals from SES and log them, so that
if we someday change our mind about using these features, the code is
already there.
It also tells future reader that we didn't forget to handle these,
simply we have reasons to not use them at this moment in time.
Closes #778

Capture and log click and open signals from SES

---

.github/workflows/codeql-analysis.yml

Update CodeQL to version 2

---

.github/workflows/codeql-analysis.yml
transport_nantes/asso_tn/templates/asso_tn/404.html
transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html
transport_nantes/asso_tn/utils.py
transport_nantes/asso_tn/views.py
transport_nantes/mailing_list/views.py
transport_nantes/topicblog/tests_topic_blog_form.py
transport_nantes/topicblog/views.py
transport_nantes/transport_nantes/urls.py

Ignore me, just want to get CI to run on this branch.

Jeff 404 etc

---

transport_nantes/press/tests.py
transport_nantes/press/views.py

Mock is guaranteed to be stable in time.

Fix test that relied on live data to pass

---

transport_nantes/asso_tn/templates/asso_tn/base_email_mobilitain.html
transport_nantes/topicblog/templates/topicblog/base_email_client.html

Replace gray with white background color in emails

---

transport_nantes/photo/templates/photo/confirmation.html
transport_nantes/photo/templates/photo/photoentry_form.html
transport_nantes/photo/views.py

closes #822 
* Added some logs to GET (form and confirmation)
* Display the photo after submission
* Make the submit button more obvious

Benja 822 photo contest improvements

---

transport_nantes/authentication/templates/authentication/account_activation_email.html

Be less distracting, less full of exclamation marks, more to the point.
Some day we need to improve the graphic design, for that we need someone who is good at that.
(I'm starting to feel like I'm interacting with methamphetamine doped puppies on our site.  Everything is so caffeinated!  It's all great!  We're glad you're here!  Click here to continue!)

Improve email auth message

---

transport_nantes/asso_tn/templatetags/don.py

Buttons are now aligned to the left like paragraphs.

Remove left padding on buttons

---

requirements.txt
transport_nantes/transport_nantes/settings.py
transport_nantes/transport_nantes/settings_local.py.DEV.template

This sets up rollbar monitoring. 
Closes #339

Add rollbar

---

transport_nantes/topicblog/templates/topicblog/communique_presse_1.html
transport_nantes/topicblog/templates/topicblog/content_email.html
transport_nantes/topicblog/templates/topicblog/content_email_client.html

Aside, small fix of improper html

Fix improperly displayed date in articles and CP

---

transport_nantes/asso_tn/static/asso_tn/mobilitains.css
transport_nantes/press/templates/press/press_list_view.html
transport_nantes/press/views.py

* Add pagination
* Change the display of the press mention card
Part of #867

Improve press mention list view

---

transport_nantes/topicblog/forms.py
transport_nantes/topicblog/models.py
transport_nantes/topicblog/templates/topicblog/base_topicblog.html
transport_nantes/topicblog/templates/topicblog/topicblogbase_list.html
transport_nantes/topicblog/templates/topicblog/topicblogbase_list_one.html
transport_nantes/topicblog/views.py

It's now easier to spot which instance is served using boldness and
color hint.
Also the "Publier" button only shows when this action is possible.
I also suggest a change in the list view layout, by centering it. It's responsive. 
Fix: Only the last item created would show, instead of the
last published one
Fix: Creation form would show scheduled_for_deletion_date field.
Closes #869

Benja clean up publication model 869

---

transport_nantes/topicblog/templates/topicblog/template_tags/item_teaser.html
transport_nantes/topicblog/templates/topicblog/topicblogbase_send_form.html
transport_nantes/topicblog/views.py

To help the person who's sending, we added a reminder before sending the
object.
Closes #870

Add a reminder and a pre-visualization of sent object

---

transport_nantes/mailing_list/templates/mailing_list/mailing_list_list_view.html

Made the table narrower and the frequency field not as big as before.
Also made the "État" field a checkbox instead of a string.
Part of #832
The other demands in the #832 issue are very reminiscent of what I've done in #884, what do you think ?

Apply cosmetic changes to ml/list

---

transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html
transport_nantes/mobilito/static/mobilito/css/address_form.css
transport_nantes/mobilito/static/mobilito/css/recording.css
transport_nantes/mobilito/templates/mobilito/address_form.html
transport_nantes/mobilito/templates/mobilito/recording.html

Apply Simon's suggestions on Mobilito design

---

transport_nantes/mobilito/templates/mobilito/tutorial.html

Hide the next page arrow on mobilito tutorial once completed

---

transport_nantes/mobilito/static/mobilito/js/geolocation_map.js
transport_nantes/mobilito/templates/mobilito/geolocation_form.html

This control allow users to search for a place and place a marker on the map on its location.
Closes #942

Add geocoder control on Mobilito map

---

transport_nantes/mobilito/forms.py

Make localisation field not required in mobilito form

---

transport_nantes/transport_nantes/tests.py

We sometimes forget to add migrations to commits, this test will check for that.

Add test that checks for missing migrations

---

requirements.txt
transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html
transport_nantes/mobilito/templates/mobilito/geolocation_form.html
transport_nantes/mobilito/templates/mobilito/recording.html
transport_nantes/mobilito/templates/mobilito/tutorial.html
transport_nantes/stripe_app/templates/stripe_app/donation_form.html
transport_nantes/topicblog/templates/topicblog/topicblogbase_edit.html
transport_nantes/transport_nantes/settings.py

This PR introduces django_compressor.
This lib compresses linked and inline JavaScript or CSS into a single cached file.
The generated file has a name that depends on its content, so it forces cache to update when its content changes.

Benja compress bundle static 362

---

transport_nantes/stripe_app/templates/stripe_app/thank_you_email.html
transport_nantes/stripe_app/views.py

Donors will receive an email thanking them for their donation.
Part of #199
Deployed on beta  :

Add mail sending on donation

---

transport_nantes/mobilito/models.py

Add missing migration

---

transport_nantes/mobilito/static/mobilito/css/mobilito.css
transport_nantes/mobilito/templates/mobilito/mobilito_session_summary.html

Fix bug discovered in #996 
Changes :
* Dropdown is not empty anymore when you are the sessio's author
* Text color is back to its original color in the modal (used to be white on white because of #990 )

Benja fix report flag display

---

transport_nantes/topicblog/templates/topicblog/content_email_client.html

The unsub class was drawing attention to the unsub button.
Closes #991

Make unsub button less visible

---

transport_nantes/asso_tn/static/asso_tn/mobilitains.css
transport_nantes/photo/templates/photo/photoentry_list.html
transport_nantes/photo/urls.py
transport_nantes/photo/views.py

Based on #963 
This add a simple, responsive and paginated view to all entries in photo contest.
Paginated to 4 items per page to save on loading time.
Added a small hover effect for desktop users.
Couldn't get the infinite loading to properly work in an hour, so dropped it.

Benja listview photo contest 986

---

transport_nantes/photo/views.py

Benja og data photo 988

---

transport_nantes/mobilito/templates/mobilito/mobilito_session_summary.html

Based on #998
This commit adds a map based on the latitude and longitude recorded for a mobilito session.
This is the same map we use for geolocation form.
Part of #981

Benja mobilito map 981

---

transport_nantes/mobilito/static/mobilito/css/session_summary.css
transport_nantes/mobilito/templates/mobilito/mobilito_session_summary.html
transport_nantes/mobilito/tests.py
transport_nantes/mobilito/views.py

This PR does a cleanup of the #997 PR.
Mostly, it's improvements on responsiveness and code quality on front-end, and a minor change in the backend to use a non GUI backend for matplotlib.

Benja merge cleanup 971

---

transport_nantes/photo/views.py

Bump the number of items displayed on photo gallery pages to 20

---

transport_nantes/photo/templates/photo/photoentry_list.html

Mobile - 1 column
Medium screen - 2 columns
Large screen - 3 columns
Closes #1048

Add a 3rd column for wider screens in photo gallery

---

transport_nantes/photo/tests.py
transport_nantes/photo/views.py

First photo's previous is the last photo,
and the last photo's next is the first photo.
Closes #1045

Make arrows circular in photo gallery

---

transport_nantes/photo/templates/photo/photoentry_list.html

A text shows if we have no photos in a gallery. This text in the paragraph is removed because it was stating the obvious.
Closes #1052

Add fallback for empty galleries and remove paragraph

---

transport_nantes/photo/static/photo/css/single_entry.css
transport_nantes/photo/templates/photo/single_entry.html

The initial design intended to make the arrows slightly overflowing the image, but on lower resolutions this rendered poorly, making images even smaller.
Instead, I embedded entirely the arrows.
The arrows do not jump visually anymore and are steadily placed.
Closes #1072

Move arrows on the same level as the image in the photo gallery

---

transport_nantes/asso_tn/static/asso_tn/mobilitains.css
transport_nantes/photo/static/photo/js/vote_system.js
transport_nantes/photo/templates/photo/single_entry.html
transport_nantes/photo/tests.py
transport_nantes/photo/views.py

Based on PR  #1075
Remove dislike button, and replace like with heart
The dislike button was drawing attention to negative feelings
instead of expressing those, we would like to only leave love
or indifference as choices.
Clicking again on the heart is equivalent to what used to be
the dislike button.
Closes #1073

Benja remove downvote button 1073

---

transport_nantes/mobilito/templates/mobilito/mobilito_session_summary.html

Add OG data to mobilito_session_summary

---

transport_nantes/photo/tests.py

This is based on PR #1076 because this has to do with like button, so to save me a merge conflict, I did base it on latest change to that part of the code. 
Fix abusive database access in photo tests
The lambda function used to poll the database every 0.5s for 5 to
check if the vote had been processed. This was causing too many
database queries that would sometimes raise table locked errors
on the CI server.
This commit fixes it by checking the feedback that comes after the
vote has been processed : once the vote processed, the server
returns a 200 response and the "success" callback is executed.
This function will change the class list of the vote button by
toggling several classes.
It goes like this :
- Default state, the user never liked the photo. Class is absent.
- User likes the …

Benja debug ci 1077

---

transport_nantes/asso_tn/static/asso_tn/mobilitains.css
transport_nantes/asso_tn/templates/asso_tn/404.html
transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html
transport_nantes/asso_tn/templates/asso_tn/index.html
transport_nantes/asso_tn/templates/asso_tn/mpanel/projects.html
transport_nantes/asso_tn/templates/asso_tn/mpanel/qui_sommes_nous.html
transport_nantes/asso_tn/templates/asso_tn/mpanel/volunteer.html
transport_nantes/mailing_list/templates/mailing_list/panel/mailing_list.html
transport_nantes/topicblog/templates/topicblog/content.html
transport_nantes/topicblog/templates/topicblog/content_mlp.html
transport_nantes/topicblog/templates/topicblog/template_tags/item_teaser.html
transport_nantes/topicblog/templates/topicblog/template_tags/item_teaser_index.html
transport_nantes/topicblog/templates/topicblog/template_tags/launcher.html
transport_nantes/topicblog/templates/topicblog/template_tags/launcher_carousel.html
transport_nantes/topicblog/templatetags/launcher.py
transport_nantes/topicblog/templatetags/test_templatags.py
transport_nantes/topicblog/tests_topic_blog.py
transport_nantes/transport_nantes/urls.py

It's all mostly a responsive change and some tweaks in font sizing, spacing and colors.
The carousel on a smaller screen makes it friendlier for mobile users, that had to face a big highway of images to get to the next content.
The front page has a special layout, so it doesn't need to be a TopicBlogItem anymore.
To change the front page's header, you may edit asso_tn/index.html, and for the projects, you may edit asso_tn/mpanel/projects.html.
Closes #1082

Redesign the front page

---

transport_nantes/photo/admin.py

It didn't serve a purpose, making it searchable was enough.
Closes #1087

Remove mail address from the admin filters

---

transport_nantes/photo/models.py
transport_nantes/photo/templates/photo/single_entry.html
transport_nantes/photo/views.py

Part of #1093
Social medias wont render our markdown, so I used bs4 to parse the rendered text and send that to social medias instead.
On our website (beta) :

Add pedestrian_issues to the OpenGraph data

---

transport_nantes/photo/templates/photo/single_entry.html

Add a back button to photo gallery

---

transport_nantes/mobilito/templates/mobilito/index.html
transport_nantes/mobilito/templates/mobilito/my_session_history.html
transport_nantes/mobilito/tests.py
transport_nantes/mobilito/urls.py
transport_nantes/mobilito/views.py

This is an easy way to find your previous sessions. You had to go through your mails to find the link to your session, that wasn't very convenient.
Closes #1101

Add "my sessions" page for mobilito

---

.github/workflows/lint.yml
transport_nantes/stripe_app/views.py

Run flake8 on all PRs

---

transport_nantes/photo/admin.py
transport_nantes/photo/templates/photo/single_entry.html

Using Chrome's responsive mode, on Samsung S8+
Currently on beta : 
On dev :
I think it definitely draws more attention than before while staying on brand. 
Closes #1112

Highlight pedestrian issues in the photo detail view

---

transport_nantes/asso_tn/middleware/sessionCookie.py
transport_nantes/stripe_app/static/stripe_app/form_flow.js
transport_nantes/stripe_app/tests.py
transport_nantes/stripe_app/views.py

Code quality improvement PR
Stripe code has revealed some ill-documented bits, it was time for a bit of cleanup.
This PR improves error handling and makes clearer the intents and what's expected as outputs and inputs.
Closes #1119
Closes #1111

Benja stripe doc and clean 1119 1111

---

transport_nantes/photo/templates/photo/index.html
transport_nantes/photo/urls.py
transport_nantes/photo/views.py

Add introductory text to the photo index page

---

transport_nantes/mobilito/templates/mobilito/mobilito_session_summary.html

Add a back to menu button on session summary

---

transport_nantes/photo/templates/photo/photoentry_list.html

Add link to photo index and a short extract from it to galery

---

transport_nantes/asso_tn/forms.py
transport_nantes/asso_tn/static/asso_tn/js/edit_username.js
transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html
transport_nantes/asso_tn/templates/asso_tn/edit_username.html
transport_nantes/asso_tn/templates/asso_tn/preferences.html
transport_nantes/asso_tn/tests.py
transport_nantes/asso_tn/urls.py
transport_nantes/asso_tn/views.py
transport_nantes/mobilito/static/mobilito/css/mobilito.css
transport_nantes/mobilito/static/mobilito/js/edit_username_in_place.js
transport_nantes/mobilito/templates/mobilito/index.html
transport_nantes/mobilito/templates/mobilito/mobilito_session_summary.html
transport_nantes/mobilito/templates/mobilito/session_history.html
transport_nantes/mobilito/templates/mobilito/session_history_line.html
transport_nantes/mobilito/tests.py
transport_nantes/mobilito/views.py

Based on PR #1126 
This PR adds the preference page that allows users to change their usernames, as long as it's available.
Closes #1117

Benja edit username 1117

---

transport_nantes/authentication/templates/authentication/account_activation_email.html
transport_nantes/dashboard/templates/dashboard/signature.html
transport_nantes/stripe_app/templates/stripe_app/thank_you_email.html
transport_nantes/topicblog/templates/topicblog/content_email_client.html
transport_nantes/topicblog/templates/topicblog/content_press_mail_client.html

It's not 2022 forever.
Closes #1170.

Fix hard-coded dates, mostly in copyright lines
