transport_nantes/topicblog/tests.py

Part of #78 
Added a test to see if the main page returns 404 while the topicblog's table is empty
Then mocked an entry to the table and verified if the page returned 200.

Fix test on main page's status

---

transport_nantes/asso_tn/static/asso_tn/mobilitains.css
transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html

Menus were breaking in the middle.
Above 992px resolution, the logo is now proportional to the width,
until it collapses at 992px. At this point it gets its normal size back
because the menu are collapsed.
Part of #134

Fix responsiveness of navbar for intermediate resolutions.

---

transport_nantes/asso_tn/utils.py
transport_nantes/topicblog/views.py

This decorator is used to secure Ajax endpoints.
With this decorator, only staff users will be able to access these
endpoints.
Closes #268

Add @StaffRequired decorator to secure Ajax endpoints

---

transport_nantes/topicblog/templates/topicblog/tb_item_edit.html

This button does a full reload of the form, which gives reassurance to
the user that the changes it did (provided it didn't submit) are not
saved.
Closes #251

Add Cancel button to TBv2 form

---

transport_nantes/topicblog/forms.py
transport_nantes/topicblog/static/topicblog/update_template_list.js
transport_nantes/topicblog/views.py

Splitting the form into two classes avoid the former default behavior of
the "template" field to be empty when the form is loaded.
Closes #250

Fix borked dropwdown on edition form.

---

transport_nantes/topicblog/static/topicblog/same_slug_warning.js
transport_nantes/topicblog/templates/topicblog/tb_item_edit.html
transport_nantes/topicblog/urls.py
transport_nantes/topicblog/views.py

Now OK to merge
This message informs the user if the slug its entering is already
in use.
The goal is to not use slugs that have already been used unknowingly.
Closes #246
Ajax endpoints have been secured with @StaffRequired decorator (see #270)
```cmd
benja@Benja-desktop:~/Documents/GitHub/tn_web/transport_nantes$ curl -I localhost:8000/tb/ajax/get-slug-dict/
HTTP/1.1 403 Forbidden
Date: Wed, 03 Nov 2021 13:20:58 GMT
Server: WSGIServer/0.2 CPython/3.8.10
Content-Type: text/html; charset=utf-8
X-Frame-Options: DENY
Content-Length: 68
Vary: Cookie
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Set-Cookie:  sessionid=un4xiufkkbnb4kuy5za09wzb4f7sugfr; expires=Mon, 02 May 2022 13:20:58 GMT; HttpOnly; Max-Age=15552000; Path=/; SameSite=Lax …
```

Add a message under the Slug Field in TBv2

---

transport_nantes/topicblog/templates/topicblog/content.html

We meant to have CTAs include a right arrow in articles.  This
corrects that omission.
Closes #272.

Add right arrow on CTA labels in TB article template

---

transport_nantes/topicblog/forms.py
transport_nantes/topicblog/models.py
transport_nantes/topicblog/tests_auth_users.py
transport_nantes/topicblog/tests_staff_users.py
transport_nantes/topicblog/tests_unauth_users.py

Update tests to integrate the change about published attribute being removed for the publication_date attribute.
These tests do not check yet the hypothesis where we try to serve an item not published yet, as all items created in the tests are published. 
However it gives us reassurance that nothing broke regarding already published items, which is a plus. 
Part of the #293  issue.

Update tbv2 tests

---

transport_nantes/topicblog/templates/topicblog/tb_item_edit.html

It introduced a breaking bug that made the slug field not save.
the suggestion feature is a nice to have one, but I'd say it's not exactly a priority either, as we have a warning if we're using the same slug as an existing article. 
Wdyt ?  
Closes  #306

Revert the suggestion feature in TBv2

---

transport_nantes/mailing_list/forms.py
transport_nantes/mailing_list/templates/mailing_list/quick_signup_m.html
transport_nantes/mailing_list/views.py

When the user got something wrong (either missing email or invalid
captcha), no error was displayed, which could lead to confusion.
Minor improvement : The mail entered in the invalid form is pre-filled
in the new form.
Closes #384
Aside, some light PEP8 formatting, in a separate commit.

Captcha error 384

---

transport_nantes/topicblog/views.py

We added a button at the end of 2021 to encourage donations.  (We
received none.)  It's not something we intended to keep long term.
Let's drop it now that the new year has started.

Drop the end of year banner

---

transport_nantes/topicblog/templatetags/markdown.py
transport_nantes/topicblog/test_tn_links.py
transport_nantes/topicblog/tn_links.py

The HTML code produced by this tag is now aware of the general context
provided by the context processor.
This means we can now check the user's login status for example.
Closes #391

Make mailinglist template tag context sensitive

---

transport_nantes/topicblog/templates/topicblog/tb_item_edit.html
transport_nantes/topicblog/views.py

The cancel button could be misunderstood, changing the wording
clears that confusion.
Added a button to return to the list of articles, which is the
function one could expect from the cancel button.
Part of #442

Rename tab in TBI and clarify buttons

---

transport_nantes/topicblog/templatetags/slug.py
transport_nantes/topicblog/test_tn_links.py
transport_nantes/topicblog/tn_links.py

Deprecate "action:" in favour of "cta:".
Part of #464.
_I actually need this rather urgently, so I'm going to do a branch deploy to prod.  We'll merge it once you LGTM, but we should be careful not to deploy other things until that's done._

Add better TBItem support

---

transport_nantes/topicblog/views.py

For choosing the publishable page, it doesn't matter a wit in what
order things were modified, only in what order they were published.
So only sort on publication date.
For the list view, it turns out to get confusing when including
publication date in sort order.  Our heads mostly remember when we
modified things, and more recent things should come first.  So do
that.
Part of #462.

Fiddle with sort order

---

transport_nantes/topicblog/models.py

Calling .now() twice would return close but not same values for
values that would be expected to be equal.
Closes #435

Fix slight time skew on save.

---

transport_nantes/press/templates/press/table_list.html

The article title become a  link (on click open on a new tab) and delete the url colum.

Improve the display of table press

---

Vagrantfile

Selenium requires a local install of Google-chrome to run.

Add google-chrome to Vagrant VM

---

transport_nantes/authentication/views.py

This allows us to send both plain text and html versions of a message
in an email.
For instance, the magic token email. 
The template doesn't contain actual html tags in it (yet), the objective is to be consistent with the rest of the code regarding emails.
Part of #419

Add html_message argument to send_mail function

---

transport_nantes/topicblog/templatetags/slug.py
transport_nantes/topicblog/test_tn_links.py

I'd inversed the label and slug.
Part of #497.

Fix order issue on slug: markdown directive

---

transport_nantes/stripe_app/views.py

Because the origin isn't a form we created but a renewal event sent from stripe, we might just save it as such.

Update the originating view and params on sub cycles.

---

transport_nantes/asso_tn/templatetags/don.py

Several things happen here :
- test_tn_links is ran by the test suite
- Among the imports, we have `from asso_tn.templatetags import don`
- don.py is subsequently imported
- In the very first lines, a global variable is created for the
templatetags to use : page_donation = reverse("stripe_app:stripe")
- Because don.py is ran, page_donation is evaluated.
- The reverse function is ran, which, in turn, calls the urlconf and a
resolver function.
- The resolver will check the root url_conf in transport_nantes/urls.py
- The urls.py is ran, in it we import
`from topicblog.views import TopicBlogItemView`
- topicblog/views.py is executed
- Inside it, we import among other things :
from .forms import TopicBlogItemForm, TopicBlogEmailSendForm
- topicblog/forms.py is executed
- In …

Fix GitHub Action module import error

---

transport_nantes/topicblog/templates/topicblog/base_email_client.html
transport_nantes/topicblog/templates/topicblog/content_email.html
transport_nantes/topicblog/templates/topicblog/content_email_client.html
transport_nantes/topicblog/templatetags/email_tags.py
transport_nantes/topicblog/templatetags/test_templatags.py
transport_nantes/topicblog/views.py

We're going to use 2 sorts of templates to display TBEmails:
- One to be displayed in mail clients, which heavily relies on inline
styles and HTML tables
- One to be displayed on our website, with a more article looking way,
that will allow the user to browse the website normally.
The 1st kind is introduced with these commits, and the 2nd has already been added in #529, and updated here to fit the current implementation of TBEmails.
On the note of templatetags, it's true that for now, one might not be able to use all those available for TBItem (mostly thinking about custom markdown ones like `[[verb]]((arg))`) although I haven't tried to display them to see how it reacts.
So far I've provided fields that I know will display properly in both templates, but lack of freedom in the _md …

Tbe view templates 532

---

transport_nantes/mailing_list/tests.py

The test initially made a few mistakes :
The quick form doesn't have a mail field when the user is connected,
and the title of the test "testing_quick_form_logged_in" implies that
the user is logged in. Instead of that simply a "s'inscrire" button
is displayed.
There isn't a captcha to fill either, as we don't ask for one for logged
in users.
The test was checking for existence of a user that never was created
"admin@mail.com"
This commit fixes the above :
- logs in a user (by adding a session cookie to the browser)
- clicks on the button without trying to fill an absent email field
- Checks for presence and correct value of the subsequently created
MailingListEvent

Fix failing test mailinglist

---

transport_nantes/topicblog/models.py

They were gibberish, copied from TBPress.  Somehow no one noticed. :-(

Improve TBLauncher comments

---

transport_nantes/topicblog/templates/topicblog/content_email_client.html
transport_nantes/topicblog/templates/topicblog/unsubscribe_from_mailing_list.html
transport_nantes/topicblog/tests_topic_blog.py
transport_nantes/topicblog/tests_topic_blog_form.py
transport_nantes/topicblog/urls.py
transport_nantes/topicblog/views.py
transport_nantes/transport_nantes/urls.py

This PR is based on #561 (TBE-create-SendRecord-532)
It adds an URL that allows the user to unsub from a mailing list by parsing the token.
A confirmation is asked from the user, and they are then shown a confirmation page.
The link is embedded inside TBEmails when they are rendered to send via emails.
Closes #406
I leave it as a draft because the tests aren't written yet.

Add unsub link 406

---

transport_nantes/topicblog/models.py
transport_nantes/topicblog/static/topicblog/email-sending-confirm.js
transport_nantes/topicblog/templates/topicblog/base_email.html
transport_nantes/topicblog/templates/topicblog/topicblogemail_send_form.html
transport_nantes/topicblog/urls.py
transport_nantes/topicblog/views.py

based on #563 
Add a confirmation window before sending a TBEmail to a mailing list.
It informs you about how many people are subscribed to a mailing list, and makes an extra step to prevent accidental sending.

Add warning before send

---

transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html
transport_nantes/asso_tn/templates/asso_tn/crowdfunding.html
transport_nantes/stripe_app/tests.py
transport_nantes/topicblog/templates/topicblog/communique_presse_1.html
transport_nantes/topicblog/templates/topicblog/content.html
transport_nantes/topicblog/templates/topicblog/content_email.html
transport_nantes/topicblog/templates/topicblog/content_launcher.html
transport_nantes/topicblog/templates/topicblog/content_press.html

In commit 70d41a8262a67edb5437e49e9098d1e67f84e614, the ul tag was
removed from a div separating the navbar from the content.
The UL tag inside it forced a small gap that was then covered by a
negative top margin ("mt-n3"). The removal of this tag made the negative
margin overlap the navbar, because it didn't have the ul space to cover.
Instead of messing with the CSS, I removed the useless ul tag alongside
its parent div (that was also useless because it had no properties).
Removing this div also removes the need to have a negative margin that
covers the gap left by the ul tag.
This negative margin was present in base_mobilitain.html but also in
most base templates, because they came from base_mobilitain.html.
Closes #599

Fix image banners overlapping the Navbar

---

transport_nantes/topicblog/templates/topicblog/base_launcher.html

TBLa aren't self served pages that require a publication to be
displayed. Instead of that, they are rendered using the `launcher`
templatetag.
Closes #602
On a side note, we might want in the future to have buttons to "activate" the display of the template but that's another for another PR. 
For now, keeping the code related to publication doesn't seem relevant in the context of TBLa.

Delete references to publication in TopicBlogLauncher base template

---

transport_nantes/topicblog/templatetags/email_tags.py
transport_nantes/topicblog/templatetags/test_templatags.py

Links used to not have scheme and host and would look like this:
`/tb/t/<the_slug>/`
This doesn't parse outside of our website.
Adding the scheme and host allows us to have complete links that are
understandable outside of our website's context e.g.:
`https://www.mobilitains.fr/tb/t/<the_slug>/`
Closes #596
tested on beta, works fine !

Fix CTA links in mail-client rendered TBEmails

---

transport_nantes/asso_tn/static/asso_tn/mobilitains.css
transport_nantes/topicblog/templates/topicblog/template_tags/item_teaser.html
transport_nantes/topicblog/templatetags/test_templatags.py

Draft because failing test
The fade-out suggests that there is more to the story, and I think
encourage the user to read want to read more.
I've no studies to support that assumption, however this is a very
common pattern in news websites.
The centered button feels more natural to me.
This visual improvement has been inspired by the news website I browse, and social medias : You are usually shown just enough to make you want to click, while the text fades out. 
Examples:
So my proposition for this :

Add fade-out effect on new index and center button

---

transport_nantes/press/models.py
transport_nantes/press/templates/press/press_detail.html
transport_nantes/press/templates/press/press_list.html
transport_nantes/press/tests.py
transport_nantes/press/urls.py
transport_nantes/press/views.py

Based on [PR](https://github.com/transport-nantes/tn_web/pull/631)
-  Saving a valid  press_mention now redirect to press:detail_item
- Add test for press:detail_item page
- Clean unused import
On the detail view, I left 2 display options

Improve pressmention saving

---

transport_nantes/press/views.py

If the url cannot be request or don’t contain open graph image, it will return an error

Improve validation of PressMention object on saving

---

transport_nantes/dashboard/templates/dashboard/index.html
transport_nantes/press/templates/press/press_detail.html
transport_nantes/press/templates/press/table_list.html

I have a question on the [issue ](https://github.com/transport-nantes/tn_web/issues/661#issuecomment-1093288064)
- Update use icon for display pressmention page
- Add link to the detail view on table list template
-  Update turn the list icon into arrow left icon

Update display press mention and dashboard

---

transport_nantes/press/views.py

If the website of the article_link doesn't have open graph data we're warning the user that the site doesn't have open graph data.

Improve add press_mention

---

transport_nantes/transport_nantes/settings.py

The LANGUAGE_CODE setting has no effect while the I18N is disabled.
See doc :
https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-LANGUAGE_CODE
Closes #674

Enable I18N to display date in French

---

transport_nantes/authentication/templates/authentication/account_activation_email.html
transport_nantes/authentication/views.py

The former mail was not coherent, mentionned accounts, and not
formatted.
This rework uses the same process we use to send TBEmails, so it's more
coherent with the rest of the code.
It looks ok on Thunderbird, Gmail, and Outlook, at least.
Closes #604

Streamline account activation mail's sending and rewording

---

transport_nantes/asso_tn/static/asso_tn/mobilitains.css
transport_nantes/topicblog/templates/topicblog/template_tags/launcher.html

The images used to stretch thin, but now keep the same aspect ratio
no matter the size of the screen.

Improve Launchers responsive

---

transport_nantes/transport_nantes/settings.py

While keeping the option to specify an email backend locally, users who don't
have it set will still be able to use django's default.

Allow devs to define locally their email backend

---

transport_nantes/topicblog/static/topicblog/same_slug_warning.js
transport_nantes/topicblog/templates/topicblog/topicblogbase_edit.html
transport_nantes/topicblog/tests_topic_blog.py
transport_nantes/topicblog/views.py
transport_nantes/transport_nantes/settings.py

Based on PR #712 
The JS used to request only TopicBlogItems slugs.
Now that we're using several models, we're requesting slugs for the
model we're using.
Closes #700

Make same_slug_warning adapt on the model we're using

---

transport_nantes/photo/admin.py

The column display can't be user.email afaik, maybe there is a way, but considering this is low priority, I guess this is better than the default

Allow admin panel to filter by and search by email instead of username

---

transport_nantes/topicblog/templates/topicblog/content_launcher.html
transport_nantes/topicblog/templates/topicblog/template_tags/launcher.html
transport_nantes/topicblog/templatetags/launcher.py

The template used to display the published item if any, even when
we requested a single item.
To not have to maintain a separate version of the template tag,
I added a "preview" flag that is set in the template that is used to
display the previews.
The index template doesn't and must not carry this flag, as the "page"
context variable is very different in this context.
Also added a fallback to help visualize if no image is provided.

Fix TopicBlogLauncher preview

---

requirements.txt
transport_nantes/authentication/views.py
transport_nantes/topicblog/views.py
transport_nantes/transport_nantes/settings.py
transport_nantes/transport_nantes/urls.py

Edit : The GiotHub Action config file doesn't include the AWS_CONFIGURATION_SET_NAME in settings_local.py, this is blocking and would also be blocking on infra while this isn't the case. 
This PR adds the webhook and configuration needed to catch and handle events coming from Amazon SES.
The configuration set added in the email's header tells AWS how to handle the notifications regarding this email.
I'm not sure about the risk of leaking the name of the configuration set ? I don't think anyone could do something with it unless they also have our credentials, so if it's alright, I could add to our settings_local template the configuration_set of beta. 
A written document is on the way about how to add your own configuration set.

Benja 714 sns

---

transport_nantes/authentication/tests_auth.py
transport_nantes/authentication/views.py
transport_nantes/topicblog/views.py

Based on #748 
This PR adds the "Sent" even handling.
It also add error handling when sending an email. If the sending is rejected, the send record associated with the email gets a 'FAILED' status, and the rest of emails is processed.
A successfully sent email is properly updated with a "SENT" status, an updated "sent_time" and AWS message id.

Benja handle ses events

---

transport_nantes/asso_tn/utils.py
transport_nantes/topicblog/views.py

We got invalid token in GET request on press mailing list
In an attempt to reproduce the error, we log more details about
it.
Adding the token + email and ID to logs will allow us to better
reproduce the conditions that lead to incorrect token.

Add more logging to email sending

---

transport_nantes/transport_nantes/settings_local.py.DEV.template

Some settings were missing (Like AWS configuration set name) compared
to infrastructure's settings.
I reorganized the settings orders to fit the order used in infra.
I also left the BASE_DIR because although it is not used in infra,
it's useful for devs that might use this template so their db is in the
right place.
Closes #789

Add missing fields and reorganize settings_local dev template

---

transport_nantes/topicblog/templates/topicblog/content_email_client.html
transport_nantes/topicblog/templates/topicblog/content_press_mail_client.html
transport_nantes/topicblog/views.py

It previously always assumed we were using the TopicBlogEmail send
record.
Using a new token that encodes the send_record_class, we can fetch
the proper send record.
Closes  #799

Make beacon_view update the proper send records 

---

transport_nantes/authentication/views.py

The user is not marked as active or confirmed until the activation email
link is clicked.
Closes #806

Create user before sending activation email

---

transport_nantes/topicblog/forms.py
transport_nantes/topicblog/models.py
transport_nantes/topicblog/templates/topicblog/base_press.html
transport_nantes/topicblog/templates/topicblog/base_topicblog.html

We don't use this attribute anymore. Its presence in templates showed
buttons that had no functionality.
Closes #462

Remove references to "servable"

---

transport_nantes/topicblog/tests_topic_blog_form.py

* Fix the DeprecationWarning:
executable_path has been deprecated, please pass in a Service object
* Fix the DeprecationWarning:
find_element_by_* commands are deprecated. Please use find_element() instead

Fix Deprecation warning of selenium

---

transport_nantes/authentication/tests_auth.py
transport_nantes/authentication/views.py

Wrong send record class was used, referred to SendRecordTransactional instead of SendRecordTransactionalAdHoc.

Fix Send Record class in Login mails

---

transport_nantes/asso_tn/templatetags/absolute_url.py
transport_nantes/topicblog/templates/topicblog/content_email_client.html
transport_nantes/topicblog/templates/topicblog/content_press_mail_client.html
transport_nantes/topicblog/templatetags/email_tags.py
transport_nantes/topicblog/templatetags/test_templatags.py
transport_nantes/topicblog/views.py

Currently deployed to beta, this branch : 
* Narrows the images inside the body, and adjust the spacing with other elements
* Adds the hero image to the email
* Update test related to images
* Add markdown to body text (was missing in body_text_2 for TBEmails) 
Aside, I made the template render using absolute urls, it doesn't change anything in prod but allow devs to send themselves emails and still see the images rendered in the mail client (Thunderbird). 
Closes #829

Benja 829 email improvements

---

transport_nantes/asso_tn/templatetags/don.py
transport_nantes/topicblog/templates/topicblog/content.html
transport_nantes/topicblog/tn_links.py

This allows us to know if we're rendering for web or email.
Email don't accept css classes, and require hardcoded styles.
Part of #840

Make inline tn_markdown context aware

---

transport_nantes/topicblog/urls.py

We kinda forgot to add the MailingListPitchView to the url paths.
Deployed to beta 22/07

Add MailingListPitchView to url paths

---

transport_nantes/topicblog/templates/topicblog/content_email_client.html

I fiddled with the absolute positioning to get a website-like result, turns out it's incompatible with Outlook and Gmail (both web and mobile), the only solution I found has been to put it below the image.

Add header title and description to email templates

---

transport_nantes/topicblog/models.py

If one fills any of the title or description field for the header,
then they must also fill the image.

Add validation on Header image

---

transport_nantes/mobilito/templates/mobilito/tutorial.html
transport_nantes/mobilito/views.py

This PR :
* tweaks the display o the  "Passer à l'enregistrement >>"  button to only show once one has read all tutorial's pages
* Force redirection to tutorial when trying to access Address form or Recording views

Benja mobilito enforce tutorial reading

---

transport_nantes/mobilito/templates/mobilito/tutorial.html

The button was too little noticeable annd would cause confusion
when user landed on the same page they've seen before, because they
didn't realise that the button was there.
Closes #890

Make the go to record button more obvious

---

transport_nantes/mobilito/static/mobilito/css/recording.css

According to this
https://usefulangle.com/post/278/html-disable-pull-to-refresh-with-css
this property should prevent the refresh to happen when the user is
scrolling the page.
closes #891

Prevent refresh on overscroll in recording page

---

transport_nantes/dashboard/templates/dashboard/index.html

This table regroups everything the former dashboard was doing, but in a
more compact way.
It is responsive.
It doesn't handle permissions checks before displaying, this is coming a bit later so it's a lighter PR to digest. 
Part of #831

Switch main dashbaord to a table

---

transport_nantes/mobilito/templates/mobilito/tutorial.html

This avoids jumpings in arrow position.

Move next page arrow to the right on top of tutorial pages

---

transport_nantes/mobilito/templates/mobilito/result_email.html
transport_nantes/mobilito/views.py

This PR is based on #944 because the mail summary contains a link to the session summary on Mobilitains website. Only the last commit is to be considered, while we didn't approve the #944 PR.
This PR makes the email more user friendly with french language, paris timezone, and less robotic phrasing. 
It includes a link, which people can share, to the session result.

Benja mail improvement 930

---

transport_nantes/mobilito/static/mobilito/css/geolocation_form.css
transport_nantes/mobilito/static/mobilito/js/geolocation_map.js
transport_nantes/mobilito/templates/mobilito/geolocation_form.html

We used to ask for location permission when the user clicked on the "Je partage ma position" button. This was not ideal because the user couldn't use the map to set their location without giving us permission to track them.
The map is now centered on Nantes unzoomed by default, and user is now only located once they click the control button to locate themselves on the map.

Allow user to select on position on map without locating themselves

---

transport_nantes/topicblog/models.py

This commit allow the TBObjects to keep the images on edit.
One should be able to save an unfinished work, but not publish it. The clean() method used to enforce the header image validation leading to a form_invalid() call when saving an unfinished work. This would prevent the images from persisting, as we retrieve the images in the form_valid() method.
Closes #922 #921

Move image field validation to publication instead of saving

---

transport_nantes/asso_tn/static/asso_tn/mobilitains.css
transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html

The navbar progressively displays fewer elements instead of hiding
everything under a hamburger menu at 992px.
Because of the addition of a new link, the links are moved to a
dropdown menu "Nos projets" at 1200px, then to a hamburger at 768px.
The donation button is always present on width > 576px, and is moved
to the hamburger menu below.

Improve navbar's hamburger responsive

---

transport_nantes/asso_tn/templates/asso_tn/base_mobilitain.html
transport_nantes/mobilito/static/mobilito/js/geolocation_map.js
transport_nantes/mobilito/static/mobilito/js/plus_minus_buttons.js
transport_nantes/mobilito/templates/mobilito/geolocation_form.html
transport_nantes/mobilito/urls.py
transport_nantes/mobilito/views.py
transport_nantes/press/static/press/js/refresh-og.js

To avoid disclosing our API key and have a better control over the API calls, we now transfer the API call to our server. Clients make requests to our server, and if CSRF token is valid, the server makes the API call and returns the result to the client.
Closes #954

Secure MAPS API key and transfer the API call to server

---

transport_nantes/mobilito/views.py

Part of #993
The issue states that we need a button to make another session, and I agree on this but we have several PR pending on session summaries, I don't want this to be a merge nightmare so I'm postponing this change for later, it's not hard anyway.

Redirect to session summary instead of thank you page

---

transport_nantes/mobilito/templates/mobilito/mobilito_session_summary.html
transport_nantes/mobilito/views.py

The message framework allows us to push ephemeral messages to the users. Sharing the link or even reloading the page will remove the message.
Part of #993

Add temporary message to thank user for making a Mobilito session

---

transport_nantes/mobilito/templates/mobilito/mobilito_session_summary.html

The most likely reason someone might report a session is because of the free field that is user provided.
The color is dark enough so it doesn't scream click me, but you can still see if it if you look for it.
Part of #1027

Move flag session button under the address field in mobilito

---

transport_nantes/mobilito/templates/mobilito/mobilito_session_summary.html

The map was taking too much space especially on smaller devices. This commit limits the height to 23% of the screen's height.
It's a compromise to be still able to interact with it while keeping it small enough.
Closes #1013

Limit mobilito's session summary's map's height

---

transport_nantes/press/views.py

Some websites will filter some scraping user agents such as python-requests.
To avoid this, we added a custom user agent to requests made to refresh og data.
Closes #1032

Add a custom user agent to requests made to refresh og data

---

transport_nantes/photo/views.py

The query used to be too permissive :
Q(user=user) could be interpreted as Q(user=<User>) but also Q(user=None).
As every anonymous profile cast a vote with user=None, the direct effect was that as long as one anonymous visitor had voted for a photo, every anonymous was marked as having voted in the past.
Closes #1054

Fix too permissive query in photo app

---

transport_nantes/photo/templates/photo/single_entry.html
transport_nantes/photo/views.py

Private browsing in production doesn't set a csrf cookie, while it's needed for the PhotoView.
The view doesn't contain a html form, but a form is generated and submitted inside the javascript code.
Closes #1050

Add ensure_csrf_cookie  decorator to PhotoView

---

transport_nantes/mobilito/templates/mobilito/result_email.html

This PR updates the mobilito session's email template to match the color used in the app, and also adds the graphs in the email (so they aren't web-only) 
Closes #1061

Benja add mobilito content graphs to email 1061

---

transport_nantes/mobilito/static/mobilito/css/mobilito.css

Contrast checker says it's ok, as the ratio is 6.17:1 The WCAG AAA requirement is 7:1, so we're close but not there yet.
Closes #1014

Make mobilito text mobilitains-gris

---

transport_nantes/utm/middleware/utm.py
transport_nantes/utm/tests.py

Some users (or bots) may try to poke our website with a URL that uses the &args= parameter before the ?args= parameter. This would cause the base_url to be set to the URL with the &args= parameter, which would cause the URL to be invalid.
Closes #1026

Fix case where base_url would include &args= if placed before '?'

---

requirements.txt
transport_nantes/topicblog/models.py
transport_nantes/topicblog/templates/topicblog/topicblogpress_index.html
transport_nantes/topicblog/test_topic_blog_part_2.py
transport_nantes/topicblog/tests_topic_blog.py
transport_nantes/topicblog/urls.py
transport_nantes/topicblog/views.py

This PR adds a view to list all published press released on a single page, in the same fashion @mcmikashi designed the press app. 
I reused his template, tweaked it a bit to fit topicblog and here it is. 
Deployed to beta, but as I'm not sure this will stay, here is a screenshot : 
(on the screenshot you see thrice the same image and nearly same title, they do have different slugs however, so this works !)

Benja create presse release index 1019

---

transport_nantes/asso_tn/static/asso_tn/mobilitains.css
transport_nantes/photo/templates/photo/photoentry_list.html
transport_nantes/photo/templates/photo/single_entry.html
transport_nantes/topicblog/templates/topicblog/content.html
transport_nantes/topicblog/templates/topicblog/content_email.html
transport_nantes/topicblog/templates/topicblog/content_mlp.html
transport_nantes/topicblog/templates/topicblog/content_press.html
transport_nantes/topicblog/templatetags/social.py
transport_nantes/topicblog/templatetags/test_templatags.py

The base templates are not specific enough to allow a single addition of the buttons. So we add them in the content templates.
Adding it on base_mobilitain.html was unsuccessful, as the buttons would show in undesired places (like the dashboard)

Add Twitter and Facebook social sharing buttons

---

transport_nantes/photo/templates/photo/photoentry_list.html

It produces a more coherent display, and it's easier to read.
Closes #1067
Before: 
After:

Make photo gallery entries even in display

---

transport_nantes/mobilito/forms.py
transport_nantes/mobilito/models.py
transport_nantes/mobilito/static/mobilito/js/edit_location.js
transport_nantes/mobilito/templates/mobilito/mobilito_session_summary.html
transport_nantes/mobilito/tests.py
transport_nantes/mobilito/urls.py
transport_nantes/mobilito/views.py

This view allows users to edit their mobilito sessions' string location field using an edit button.
The edit button is only visible to the user who created the mobilito session, or the persons with the permission to edit mobilito sessions.
Part of #1022

Allow users to edit their MobilitoSession's location field

---

transport_nantes/mobilito/static/mobilito/js/geolocation_map.js

If the reverse geocoding failed, we would not have the lat/lng in the form's fields, while we had access to this information. By setting the field's values before the reverse geocoding, we can be sure to have the lat/lng even if the reverse geocoding failed.
Closes #1084

Save lat/lng in form's field before reverse geocoding

---

transport_nantes/photo/static/photo/css/single_entry.css
transport_nantes/photo/templates/photo/single_entry.html

The text under the picture would get sometimes pushed too far at the bottom and some may think there isn't even a text.
Closes #1104

Improve responsive in photo gallery

---

transport_nantes/transport_nantes/settings.py

The getattr allows to have a default value if the setting is not even defined in the settings_local.py file, which allows us to even not have to define on infra.
This feature is for dev env only and meant to ease the use of ngrok for local development.
Allowing ngrok subdomains in CSRF_TRUSTED_ORIGIN allows to use POST requests from ngrok subdomains (notably to login)
Because this is locked to a dev environment only, this doesn't raise any security issue on production.
closes #1124

Add non-mandatory settings for ngrok

---

transport_nantes/mobilito/templates/mobilito/index.html
transport_nantes/mobilito/templates/mobilito/session_history.html
transport_nantes/mobilito/templates/mobilito/session_history_line.html
transport_nantes/mobilito/tests.py
transport_nantes/mobilito/urls.py
transport_nantes/mobilito/views.py

This PR adds :
* A publicly accessible history for any given user using the sha1_identifier field (`/mobilito/session/u/<sha1_identifier>`)
* A username display under the location. This username isn't editable just yet, that is to come in later commits.
Hotspots for this PR : 
* I changed responsive a bit to fit a 3rd button to access your own history.
* I added a "Contributions récentes" feed on mobilito's index, tell me what you think. It's the 10 latest contributions.
* Username display: Pay closer attention to how username is fetched, I implemented a @property and a setter on this field.
Closes #1115

Benja mobilito session feed 1115
